[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"


[[repos.hooks]]
id = "end-of-file-fixer"


[[repos.hooks]]
id = "trailing-whitespace"


[[repos.hooks]]
id = "check-json"


[[repos.hooks]]
id = "check-toml"


[[repos.hooks]]
id = "check-yaml"


[[repos.hooks]]
id = "check-added-large-files"


[[repos.hooks]]
id = "check-ast"


[[repos.hooks]]
id = "detect-private-key"


[[repos.hooks]]
id = "check-merge-conflict"


[[repos.hooks]]
id = "check-case-conflict"


[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.16.4"


[[repos.hooks]]
id = "ruff"
args = [
    "--fix",
]

types_or = [
    "python",
    "pyi",
]


[[repos.hooks]]
id = "ruff-format"
types_or = [
    "python",
    "pyi",
]


[[repos]]
repo = "https://github.com/pre-commit/mirrors-mypy"
rev = "v2.3.1"


[[repos.hooks]]
id = "mypy"
additional_dependencies = [
    "fastapi-users[sqlalchemy]",
    "fastapi",
    "pydantic",
    "pydantic-settings",
    "sqlalchemy",
    "dishka",
    "pytest",
    "pytest-asyncio",
    "httpx",
    "testcontainers",
]
